# Serveur alfresco
alfresco:
  image: alfresco-community-base:5.0.d
  container_name: alfresco
  links:
    - mysql
  ports:
    - "8080:8080"
  volumes:
    - ./data/alfresco:/srv/alfresco
  environment:
    - ALFRESCO_DB_HOST=mysql
    - ALFRESCO_DB_USERNAME=root
    - ALFRESCO_DB_PASSWORD=admin

# Serveur de base de données MySQL pour alfresco
mysql:
  image: mysql
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=alfresco
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
